travis:
  secure:
    BINSTAR_TOKEN: JuBcC0mePlBtk8W4y6hvs+mkLmSUIRIvhE22iJc2aDzc/GNgFRni+b1X1QAd0OkLoUMFakQkWxQaq2nmMBIDdroZCsqL6EACMpW1aGR627MREZ2XyUyxqA9AP+/cCnjAhAlxkrz/AyQ9heKmfNNLOQVQujE3jWKnK5L2n37MyT3SP/DIcRbvWnAuhjHBNgTo4Gt4VrmiZ+OslJWJlSv7FIFPZ/1Nzh/dg0l4FxeRJ8bhAIw8W/VlgPGABk8CBdLnaJC+4rA6WvEGjkc8J1tAuHIi0fSZaJO9t1ilHKvXHj7VKuZvCOg/CZdJ8/vnaMDLHcrTZLW/b9qvv6D8saJta4QHJWn2dFdocCnZdRfkIIOJpo73Cn2Tbjikl7cUf9cmnT5OyDznKyb/7nLUiWr620NizWBu5MA2qSGs1riFnS/qIn5UJJIbu3CVYH/XN/4C4/QlMtrWO+snZqjlArsApCqKUIJDe3ss5B3XPv8UUAVnDNQ5QEGxppUOGYsYaEU2mUAev1tQtGA+wVM8ROCC7mLsVDkWSSRhycDw80G9/kn4VhcS6IOwHldxZWbaDK6NJysKmlCK5xrNZ4vJXEId01LtYNKg7oDdXm0FMAWAQxgyqWfI5VPKyA/djmmg8KptCavSXXXPK6yyakNrfvAN05lF/IhlblOrXXxyQwyCiIA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
