travis:
  secure:
    BINSTAR_TOKEN: jgONIcE7A/V7zVLzd569WeltvGther5eWTBoCCTG8Huz8+FtnvgTX0AtZqqARbNImldaLD2+0a2cr637C7apY1+YkSfDg3HuQCpM61iRPtOQBUyEY4hfNWXN2t/nI2xGsU54Pd9/wemTAM70Oz2iuSEQQio/o0PSCWUmQ/NO0cc8pWytmaguQ6f1bzBzSNXBFxxvjoenGdS5d9TD1RvIcAV1GPhM6pH1J1li6A0ytIPJ95KB5mhQc5VAMR5JoTnE2GDYZ7GkVGWXZSrI8tg2YFVaQcJCzD+JEZgiTrywp+Dlwoli737AuGKdKb/YL9XUM/Zfk3HEBB15Z3PlSJ0sltppm9iyBQ+qIkm7Yw6KfkuswPogYNopg5ZU7Sz7gWg2z8QEVVHO8aCg40rYfG0WskmbFlu+BXf54XCqi3YMyLOQGzzlKqDNeVJx+48YtWHbPzhOaDnVlmOHAIDkr/c/QUoC/jZfJqpaIju64kF/mnyOMDijmvNTc63c0nPZdbiZDdEaBKwmNUVItPQdkWM81VqdywTVO2md4h2RgoKlM8AZyENK1l4w/dFJyRj3AXEM9c2Zchq4BlFVb+v90etK3grNO6V1mvKohdATSK6+t5yupMb8I6j2O2dQQrIo/BVTeo2gOjzD/dwrnw9ki2EttSQvn/ACs+ojrY6RBWA9or0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
