travis:
  secure:
    BINSTAR_TOKEN: nZTkxucJnC8/J1AbUiU0PuYFDrf0SZ3Ofxxp8laGg6fR9D2w5ss9eKezWAOipg854HRjwKRhJsyaXdNDxOX7QpSW1fX/pVk6swQsEKD1zWuLaaP8k51hoysY6RJnyT/4YHAJOIvERQrLX1sFpjYyFYKthyhS0LRGVbGsTNM+RAdwMjacxsVLrBDjuM58ZGL2QvJVBRc1dKZQLohTaIgsVmWJbZ1rbZ8hvLApptpSSI6IZVi8IPMr+4BNAwPPR2Pdir56tdqFMdfxpGEAoM1xklRvUufUeNRTSKIfodRNkXvoHOkB2zLluWZ8p0Q3G05pWiLwEDw/ia52HHpD+Z3DgOvbHuzSVRNY8mk3bvEymcs1sRqarx7HOuk0YsP/Or3l8XEii8WdB4X2OMOpCdl89yNIn4T5IKVTKblhzxSEVh5vCp2LWNKtt4vHIcienn5ygGkpRT/TBaJghbVe4wYC+uU5rBcMFEA5aD0gAQ2xg1piLON/tnibbyFniPbYNzh1PLRl1t7c0bUiwvrHaKaDZiDqdVDswZG/A43tZUZ29QmjWoHocDh7p1T/VdheQKLptH+OCRJwFbryvgxAuHkmcXKy8THqSe1KCbGAqYOIcfr75O6hAZZOv6C+38XETe2kgpzWYI3h2dWJDTP78zTBjSYbPj4KqYeGla2eBnA3z+Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
